const express = require('express');
const router = express.Router();
const rideController = require('../controllers/ridecontroller');
router.get('/available', rideController.getAvailableRides);
router.get('/active-demands', rideController.getActiveDemands);
router.get('/withdrawal-history/:driverId', rideController.getWithdrawalHistory);
router.get('/passenger-history/:userId', rideController.getPassengerHistory);
router.get('/driver-rides/:driverId', rideController.getDriverRides);
router.get('/:rideId', rideController.getRideById);
router.post('/publish', rideController.publishRide);
router.post('/book-request', rideController.requestBookRide);
router.post('/accept-request', rideController.acceptBookingRequest);
router.post('/reject-request', rideController.rejectBookingRequest);
router.post('/create-payment-order', rideController.createPaymentOrder);
router.post('/verify-payment', rideController.verifyPayment);
router.post('/start-ride', rideController.startRide);
router.post('/withdraw-earnings', rideController.withdrawEarnings);
router.post('/complete', rideController.completeRide);
router.post('/cancel-ride', rideController.cancelRide);
module.exports = router;